/**
 * Dump a done baseline run as data-only SQL (for fixtures/baseline.sql).
 */

import { writeFile } from "node:fs/promises";
import type pg from "pg";
import { createPool } from "./db.ts";

function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(arr: string[]): string {
  if (arr.length === 0) return `ARRAY[]::text[]`;
  return `ARRAY[${arr.map(sqlStr).join(",")}]`;
}

function sqlNullableTs(value: Date | string | null): string {
  if (value == null) return "NULL";
  const d = value instanceof Date ? value : new Date(value);
  return sqlStr(d.toISOString());
}

export async function dumpBaselineSql(
  databaseUrl: string,
  runId: string,
  outPath: string,
): Promise<{ resultCount: number }> {
  const pool = createPool(databaseUrl);
  try {
    return await dumpWithPool(pool, runId, outPath);
  } finally {
    await pool.end();
  }
}

async function dumpWithPool(
  pool: pg.Pool,
  runId: string,
  outPath: string,
): Promise<{ resultCount: number }> {
  const run = await pool.query<{
    id: string;
    label: string;
    status: string;
    created_at: Date;
    finished_at: Date | null;
  }>(
    `SELECT id, label, status, created_at, finished_at
     FROM runs WHERE id = $1::uuid`,
    [runId],
  );
  if (!run.rowCount) throw new Error(`run not found: ${runId}`);
  const r = run.rows[0]!;
  if (r.status !== "done" && r.status !== "failed") {
    throw new Error(`run ${runId} status=${r.status}; need done or failed`);
  }

  const jobs = await pool.query<{
    id: string;
    run_id: string;
    command: string;
    status: string;
    attempt: number;
    finished_at: Date | null;
    priority: number;
  }>(
    `SELECT id, run_id, command, status, attempt, finished_at, priority
     FROM jobs WHERE run_id = $1::uuid ORDER BY priority, id`,
    [runId],
  );

  const attempts = await pool.query<{
    id: string;
    job_id: string;
    attempt_no: number;
    worker_id: string;
    lease_token: string;
    status: string;
    started_at: Date;
    finished_at: Date | null;
  }>(
    `SELECT ja.id, ja.job_id, ja.attempt_no, ja.worker_id, ja.lease_token::text,
            ja.status, ja.started_at, ja.finished_at
     FROM job_attempts ja
     JOIN jobs j ON j.id = ja.job_id
     WHERE j.run_id = $1::uuid
     ORDER BY ja.job_id, ja.attempt_no`,
    [runId],
  );

  const results = await pool.query<{
    id: string;
    attempt_id: string;
    run_id: string;
    test_id: string;
    source: string;
    title_path: string;
    status: string;
    duration_ms: number;
    hit_lines: string[];
    received_at: Date;
  }>(
    `SELECT id, attempt_id, run_id, test_id, source, title_path, status,
            duration_ms, hit_lines, received_at
     FROM test_results WHERE run_id = $1::uuid
     ORDER BY received_at, test_id`,
    [runId],
  );

  if (results.rowCount === 0) {
    throw new Error(`run ${runId} has 0 test_results`);
  }

  const lines: string[] = [
    `-- Data-only seed for the HTML UI demo.`,
    `-- Generated by: npm run cli -- run-full (run ${runId}, original status=${r.status})`,
    `-- Apply after schema.sql migrate.`,
    `-- Run row is stored as status=done so serve-ui treats it as a baseline corpus.`,
    ``,
    `BEGIN;`,
    ``,
    `INSERT INTO runs (id, label, status, created_at, finished_at) VALUES`,
    `  (${sqlStr(r.id)}, ${sqlStr(r.label)}, 'done', ${sqlNullableTs(r.created_at)}, ${sqlNullableTs(r.finished_at)});`,
    ``,
  ];

  if (jobs.rowCount) {
    lines.push(`INSERT INTO jobs (id, run_id, command, status, attempt, finished_at, priority) VALUES`);
    lines.push(
      jobs.rows
        .map(
          (j, i) =>
            // Normalize job/attempt to done for fixture boot (corpus, not audit).
            `  (${sqlStr(j.id)}, ${sqlStr(j.run_id)}, ${sqlStr(j.command)}, 'done', ${j.attempt}, ${sqlNullableTs(j.finished_at)}, ${j.priority})${i === jobs.rows.length - 1 ? ";" : ","}`,
        )
        .join("\n"),
    );
    lines.push(``);
  }

  if (attempts.rowCount) {
    lines.push(
      `INSERT INTO job_attempts (id, job_id, attempt_no, worker_id, lease_token, status, started_at, finished_at) VALUES`,
    );
    lines.push(
      attempts.rows
        .map(
          (a, i) =>
            `  (${sqlStr(a.id)}, ${sqlStr(a.job_id)}, ${a.attempt_no}, ${sqlStr(a.worker_id)}, ${sqlStr(a.lease_token)}::uuid, 'done', ${sqlNullableTs(a.started_at)}, ${sqlNullableTs(a.finished_at)})${i === attempts.rows.length - 1 ? ";" : ","}`,
        )
        .join("\n"),
    );
    lines.push(``);
  }

  lines.push(`INSERT INTO test_results`);
  lines.push(
    `  (id, attempt_id, run_id, test_id, source, title_path, status, duration_ms, hit_lines, received_at)`,
  );
  lines.push(`VALUES`);
  lines.push(
    results.rows
      .map(
        (tr, i) =>
          `  (${sqlStr(tr.id)}, ${sqlStr(tr.attempt_id)}, ${sqlStr(tr.run_id)}, ${sqlStr(tr.test_id)}, ${sqlStr(tr.source)}, ${sqlStr(tr.title_path)}, ${sqlStr(tr.status)}, ${tr.duration_ms}, ${sqlTextArray(tr.hit_lines ?? [])}, ${sqlNullableTs(tr.received_at)})${i === results.rows.length - 1 ? ";" : ","}`,
      )
      .join("\n"),
  );
  lines.push(``);
  lines.push(`COMMIT;`);
  lines.push(``);

  await writeFile(outPath, lines.join("\n"), "utf8");
  return { resultCount: results.rowCount ?? 0 };
}

export async function resolveDatabaseUrl(): Promise<string | null> {
  if (process.env.SIEVE_DATABASE_URL) return process.env.SIEVE_DATABASE_URL;
  try {
    const { readFile } = await import("node:fs/promises");
    const path = await import("node:path");
    const { fileURLToPath } = await import("node:url");
    const sieveRoot = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      "..",
    );
    const raw = (await readFile(path.join(sieveRoot, ".database-url"), "utf8")).trim();
    return raw || null;
  } catch {
    return null;
  }
}
